# Generated by Django 5.0.6 on 2024-05-31 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_producto'),
    ]

    operations = [
    ]
