# Generated by Django 5.0.6 on 2024-05-31 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20240530_2319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='cantidad',
            new_name='stock',
        ),
    ]
