# Generated by Django 5.0.6 on 2024-07-17 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_precio_producto_precio_base_precioporciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio_base',
            new_name='precio_15_porciones',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_20_porciones',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_25_porciones',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_30_porciones',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
        ),
        migrations.DeleteModel(
            name='PrecioPorciones',
        ),
    ]
